# Generated by Django 4.1.3 on 2023-03-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dibursement',
            new_name='disbursement',
        ),
    ]
