# Generated by Django 4.1.3 on 2023-03-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_alter_project_agreement_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
